### ISSUE TITLE
trouble with blotter

### ISSUE THREAD

**Issue by adamatusz** [braverock/quantstrat#108]
I have trouble installing and I care a lot about my thesis.
 R Studio displays a message:

Downloading GitHub repo braverock/blotter@master
Your system is ready to build packages!
√  checking for file 'C:\Users\Adam Matuszczyk\AppData\Local\Temp\Rtmpst8q7W\remotes34c40e6e9d\braverock-blotter-16349ee/DESCRIPTION' ...
-  preparing 'blotter':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'blotter_0.14.7.tar.gz'
   
Installing package into ‘C:/Users/Adam Matuszczyk/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'blotter' ...
** using staged installation
** libs
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-3.6.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c calcPosAvgCost.c -o calcPosAvgCost.o
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-3.6.1/include" -DNDEBUG          -O2 -Wall  -std=gnu99 -mtune=generic -c init.c -o init.o
C:/RBuildTools/3.5/mingw_64/bin/gcc -shared -s -static-libgcc -o blotter.dll tmp.def calcPosAvgCost.o init.o -LC:/PROGRA~1/R/R-3.6.1/bin/x64 -lR
installing to C:/Users/Adam Matuszczyk/Documents/R/win-library/3.6/00LOCK-blotter/00new/blotter/libs/x64
** R
** data
** demo
** byte-compile and prepare package for lazy loading
Blad krytyczny: nie mozna otworzyc pliku 'C:\Users\Adam': No such file or directory

ERROR: lazy loading failed for package 'blotter'
* removing 'C:/Users/Adam Matuszczyk/Documents/R/win-library/3.6/blotter'
Error: Failed to install 'blotter' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Adam Matuszczyk/AppData/Local/Temp/Rtmpst8q7W/file34c4dbd7d3f/blotter_0.14.7.tar.gz’ had non-zero exit status

with packages "devtools", "FinancialInstrument", "PerformanceAnalytics" are ok.

[Downloading GitHub repo braverock.pdf](https://github.com/braverock/quantstrat/files/3537997/Downloading.GitHub.repo.braverock.pdf)

Please help me,

**Comment by jaymon0703** [comment]
Hi Adam, have you tried removing the white space in your folder name with your name and surname?

**Comment by adamatusz** [comment]
Hi Jasen,

Yes, I did it and I caused even more trouble, so I quickly returned to the default directory and wrote to you. I know this may be a problem, but maybe there is another way, not to reinstall the system.

Best Regards

**Comment by jaymon0703** [comment]
Hmm, the error message is quite clear that it cannot find a file or directory named "C:\Users\Adam".

What issues did you experience when you removed the whitespace?
Have you installed _blotter_ successfully before on your machine?

**Comment by braverock** [comment]
Adam,  I'll give you two options, I hope one should work.

One is to start a vanilla R session with `R --vanilla` or make sure that no other packages are loaded in your `.Rprofile` before restarting R.  Then try using `remotes` instead of devtools, as it is significantly lighter weight:

    # install.packages('remotes')
    remotes::install_github('braverock/blotter')

Recent versions of `devtools` have abandoned their own heavier weight `install_github` to use the version from `remotes`, but it is re-exported, so this might cause some difficulties.

The other option is to clone the package from github, and then use `R CMD build` and `R CMD INSTALL`

I will have a Windows machine I can test from available tomorrow.

**Comment by adamatusz** [comment]
Jasen,

1. Everything disappeared, I even had problems logging out. Fortunately, the "admin account" was working and I could return to the option with with the whitespace.

2. Yes, I tried  older version RStudio 3.4.1 direct from .zip _install.packages("f:/quantstrat/blotter_0.9.1741.zip"_, but it didn't really work and kept throwing "blotter / quantsrat" all the time.

Hi Brian,

I will actually wait until tomorrow it will be better and I will try your solutions today.

Best Regards

**Comment by adamatusz** [comment]
Gentlemen, everything is fine with R --vanilla I overcame the problem. Full respect for your knowledge and many thanks.

Best Regards

**Comment by jaymon0703** [comment]
Glad to hear Adam.

**Comment by braverock** [comment]
blotter 0.9.1741 is years old.  I would definitely not expect that to work.

from inside RStudio, you can *build* the package if you've cloned it from github, then you could install from the terminal.

**Comment by damanisme** [comment]
The best way I found to fix this was to reinstall one of the prereqs for the package which is PerformanceAnalytics to ensure you have the version greater than .14, since blotter requires a version greater than that number:

Step 1: install.packages("PerformanceAnalytics")
Step 2: remotes::install_github("braverock/blotter")

# If you are looking to install quanstrat at this point it should install for you with the following code:

remotes::install_github("braverock/quantstrat", force = TRUE)
