### ISSUE TITLE
AAPL.rda in the data is preventing me from installing quantstrat

### ISSUE THREAD

**Issue by jerryzhujian9** [braverock/quantstrat#117]
I am using R 3.3.3. It seems that the newer version of R has a different data storage format. Would it be possible for your to make AAPL.rda compatible with older version of R? 

p.s. installation note:
---------
** help
*** installing help indices
*** copying figures
** building package indices
Warning: file ‘AAPL.rda’ has magic number 'RDX3'
  Use of save versions prior to 2 is deprecated
Error : restore file may be from a newer version of R -- no data loaded
ERROR: installing package indices failed

**Comment by jaymon0703** [comment]
Hi @jerryzhujian9 this problem was first reported in October last year. See https://github.com/braverock/quantstrat/issues/110#issuecomment-542388053. I am not sure it is wise to maintain 2 data formats for different versions of R, before and after R 3.5. Your version 3.3.3 was released in March 2017 and there have been 13 releases since then. Is there any reason you would not like to upgrade R instead?

**Comment by jerryzhujian9** [comment]
I understand it is really the R's issue. But I am stuck with my current mac OS X version and a tons of R libraries.... Thanks for your quick response though.

**Comment by jaymon0703** [comment]
No worries. Good luck and thanks for closing the ticket.
