### ISSUE TITLE
Problem when using a Rule of type Order with a Chain Rule

### ISSUE THREAD

**Issue by edward-wilson** [braverock/quantstrat#49]
I am trying to use a `rule` of type: `order` in my strategy but it is giving an error due to `closed.orders` object doesn't exist.  The reason is in the `applyRules` function, specifically in the switch case for the `rule` `type`, when there is a `rule` of type `order`,  `if (length(strategy$rules[[type]]) >= 1)` evaluates to true, which in turn means the `else` clause does not get processed which is where `closed.orders` is set. This causes a problem when it goes on to evaluate the `rules` of type `chain`, when `if (!is.null(closed.orders))` is evaluated, the `closed.orders` object doesn't exist. I am very unsure of my implementation of the `order` `rule`, but this problem makes me think add a `rule` of type `order` like a normal `enter` or `exit` rule at all?  I am trying to use it to allow me to modify open orders (such as profit targets) when a signal occur. Im not even sure if this is the correct approach. Is there any documentation or examples anywhere doing this? I've had a good look but couldn't find anything.

**Comment by braverock** [comment]
The default order processor in quantstrat is `ruleOrderProc`.

This is described in some detail in the documentation for `applyRules` and for `ruleOrderProc`.

You haven't posted a reproducible example, so I can't evaluate whether there is an issue here or not.  I suspect that you probably did not define `ruleOrderProc` in an `order` slot along with your custom rule, which you did not provide, or call `ruleOrderProc` from your custom rule.

Also as described in the documentation, rules in the `order` slot will only be checked when there is a chance that open orders need to be acted on.

There is quite a lot of documentation in quantstrat about writing custom rules, and the consequences of various decisions that you make.

**Comment by edward-wilson** [comment]
Could you please tell me where the documentation is for writing custom rules? I've  spent a lot of time going through the source code of the functions but some examples/documentation is what I need!

**Comment by braverock** [comment]
A rule function is just a function.  It should have the same signature as ruleSignal, per the discussion in ?applyRules and ?add.rule, so that the dimension reduction code will work..  

Once inside your custom rule, you'll have access to all the current state of mktdata, the order book, and the blotter environment, and can do what you want.  By that point in the call chain, there are no training wheels.  

You can examine the code and documentation for that various example rules shipped with quantstrat (e.g. ruleSignal and ruleOrderProc for relatively complex handling, and the various rules in rebalance.rules.R for rebalance actions, and ruleRevoke for an example that manipulated existing orders based on a new signal.)

Or, you can provide a minimal reproducible example and a specific question that demonstrates the problem you're having.

**Comment by edward-wilson** [comment]
As a specific question: How can I add a rule that, upon `sigcol = x` & `sigval = TRUE` will modify/replace any open orders to have `order.price = Y`.

In my case, the `sigcol` triggers an entry rule with a Max Position Size of 1 contract. There is a chained child rule attached to this entry rule which sets the Profit target. Each time the entry rule is triggered again during the trade, I want to modify/replace the `order.price` of the Profit target.

**Comment by braverock** [comment]
This is not a support forum, and it appears clear that this is not a bug.

Have you tried setting replace=TRUE in your take profit rule triggered by ruleSignal, per the documentation?

If you feel that you have an actual issue in quantstrat, then post a minimal reproducible example.
