### ISSUE TITLE
Quanstrat multiple concurrent signals.

### ISSUE THREAD

**Issue by xenmind** [braverock/quantstrat#60]
How does Quantstrat deal with the situation where there are more entry signals on different securities than the maximum allowable number of open positions or available funds? E.g. My system generates 10 entry signals (no open orders), but I have a constraint for 3 open positions only: how are the 3 signals chosen from the 10 candidate entries? Ideally, I'd like to use a custom function to rank the entry signals and have the top 3 selected. If it's possible how might this concurrent signal ranking be done?

**Comment by braverock** [comment]
@xenmind, sorry I didn't comment on this earlier, but the issues list is really for reporting bugs in quantstrat, not really a discussion forum.

I'll try to answer your question.

You already have the ability to filter signals.  Write another signal function, that is the last signal specification, and filter them there.  So your ranking function would fire if any (or more than *x*) of the other signals are TRUE, and then you'd make some meta-decision.

You can also do this in the order sizing function, since order sizing has access to all the available point in time data.
