### ISSUE TITLE
Recommended labels

### ISSUE THREAD

**Issue by prichards78** [braverock/quantstrat#63]
Hi, I would like to know what are the recommendations when labeling indicators and signals, due to the fact that quantstrat saves all the information in the same `xts` object, mixing market prices with the rest of the data, which can cause a conflict in order processing when the prices are being searched inside this monolithic object (usually named `mktdata`).

What I've seen so far in some blogs/tutorials is to avoid the names Open/High/Low/Close, which would be the most clear and important recommendation. But the functions that manipulate prices (from [quantmod](https://github.com/joshuaulrich/quantmod)) go beyond that, employing case insensitive [`grep`](https://github.com/joshuaulrich/quantmod/blob/master/R/Price.transformations.R#L154) searches which complicates the correct use of labels.

For example, the function [`getPrice`](https://github.com/joshuaulrich/quantmod/blob/master/R/Price.transformations.R#L19) (used extensively by quantstrat in [order processing](https://github.com/braverock/quantstrat/blob/master/R/ruleOrderProc.R#L182)) also searches for strings like `price` and `trade` (even before the more common `close` name) when its argument `prefer` is `NULL`. So those are also strings to avoid.

Also, even when selecting a specific column like the Low price, the case insensitive `low` is actually searched in the column names, and if more than one match is found, [the first one is used](https://github.com/braverock/quantstrat/blob/master/R/ruleOrderProc.R#L196). So another recommendation would be to always set the OHLC columns first in the `mktdata` object.

Are there any other strings to avoid or other precautions when labeling components?

**Comment by braverock** [comment]
This isn't really a support forum, and you're not reporting a bug or offering a feature improvement.

'label' should be unique, and you have it available for use in later functions, like signals.  if you're writing custom indicator functions, you can make the column names of what those indicators return something unique and easy to search for.

you say that getPrice 

> searches for strings like price and trade (even before the more common close name) 

but last time I checked, there are exactly *one* 'Close* message per day per instrument and *millions* of Bid/Ask `price` messages and also thousands to millions of `trade` messages per instrument per day.  It makes perfect sense to search for the messages in the order of their actual market precedence.  Of course, `prefer` will always tell getPrice what to do, otherwise it guesses and tries to help you out.  `quantstrat` will set `prefer=close` on OHLC data  if you do not supply a preference in most cases.

Your comment about order of columns doesn't make a lot of sense to me either.  The only way your OHLC columns wouldn't be first is if you constructed a market data object which had the columns in a different order.  the retrieved or passed in market data columns will always come before indicator or signal columns.

Make your function use useful, unique names.  Use the labels to create additional, informative uniqueness.  `quantstrat` will make the best guesses that it can, but ultimately naming things is hard, and it is your responsibility.

**Comment by prichards78** [comment]
Hi Brian, maybe I was too broad in the question, I was trying to provide some context to the subject and I added more noise than information.

The concrete question is: **what are `quantstrat` keywords that must be avoided in labels?**

I understand that this is not a bug in the sense that the program won't crash if I use the string `price` inside a label within a OHLC dataset (e.g., `log_price`, which was my particular case), but the results will be far from expected.

I used the term "recommendation" before but that may be to imprecise for this question, because that implies an option (to use or not those labels), but really they should be forbidden because they disrupt the program normal operation.

I don't expect `quantstrat` of course to check for the user what string not to use inside labels, but I also didn't see a precise list of those strings (maybe I missed it), and I regarded that as an issue in the documentation (which I don't see as minor), but maybe I should continue this in the mailing list.

**Comment by prichards78** [comment]
> quantstrat will set prefer=close on OHLC data if you do not supply a preference in most cases.

Inside `ruleOrderProc()`, in the processing of orders, if a [particular order doesn't have `prefer` set](https://github.com/braverock/quantstrat/blob/master/R/ruleOrderProc.R#L112) and the [argument `prefer` itself is not present](https://github.com/braverock/quantstrat/blob/master/R/ruleOrderProc.R#L89), which is the default situation, `prefer` will be left to `NULL` (not `close`), causing `getPrice` to look for strings like `price` and `trade` before `close`.

And I'm sorry if I implied that that is not the correct order (I don't have much experience to make that judgment), but the end result will be something unexpected to a new user (without any noticeable warning of it happening), and I don't see that it is obvious (maybe because of my lack of experience) that those kind of string should be avoided in OHLC data when issuing a market order without setting `prefer` (which is, I believe, a very common scenario, I'm basing myself in the [examples provided](https://github.com/braverock/quantstrat/blob/master/demo/luxor.1.strategy.basic.R)).
